import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import FloatingShape from "@/components/FloatingShape";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      > 
      
        <FloatingShape color='bg-green-500' size='w-64 h-64' top='top-[-5]' left='left-[10]' delay={0} absolute='absolute' />
        <FloatingShape color='bg-emerald-500' size='w-48 h-48' top='top-[70%]' left='left-[80%]' delay={5} />
        <FloatingShape color='bg-lime-500' size='w-32 h-32' top='top-[40%]' left='left[-10%]' delay={2} /> 
        {children}
        
       
      </body>
    </html>
  );
}
